swagger: "2.0"
info:
  title: Game Management API
  description: API for match and match odds management.
  version: 1.0.0
host: localhost:8080
schemes:
  - http
securityDefinitions:
  basicAuth:
    type: basic
paths:
  /match:
    post:
      tags:
        - "match"
      summary: "Add a new match"
      description: "Create a simple match without any odds"
      operationId: "createMatch"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Match object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/MatchInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/MatchResponse'
        "500":
          description: "operation Failure"
        "400":
          description: "invalid request"
  /match/{id}:
    get:
      tags:
        - "match"
      summary: "Find match by ID"
      description: "Returns a single match with its odds"
      operationId: "findMatch"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of match to return"
          required: true
          type: number
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/MatchResponse'
        "404":
          description: "Match not found"

    put:
      tags:
        - "match/{id}"
      summary: "Update an existing match"
      description: ""
      operationId: "updateMatchDetails"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of match to return"
          required: true
          type: number
        - in: "body"
          name: "body"
          description: "Match object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/MatchInput"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "200":
          description: "Successful operation"

    delete:
      tags:
        - "match"
      summary: "Delete a match by ID"
      description: "Delete a match"
      operationId: "deleteMatch"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the match that needs to be deleted"
          required: true
          type: "number"
      responses:
        "200":
          description: "Deleted match"
        "500":
          description: "Failure of operation"

  /match/odd/{id}:
    post:
      tags:
        - "match odd"
      summary: "Add a new match odd"
      description: ""
      operationId: "createMatchOdd"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of match"
          required: true
          type: number
        - in: "body"
          name: "body"
          description: "Match odd object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/MatchOddInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/MatchOddResponse'
        "500":
          description: "operation Failure"
        "400":
          description: "invalid request"
        "404":
          description: "match not found"

    put:
      tags:
        - "match odd"
      summary: "Update an existing match odd"
      description: ""
      operationId: "updateMatchDetails"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of match"
          required: true
          type: number
        - in: "body"
          name: "body"
          description: "Match odd object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/MatchOddInput"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "200":
          description: "Successful operation"

    delete:
      tags:
        - "match odd"
      summary: "Delete a match odd by ID"
      description: "Delete a match odd"
      operationId: "deleteMatchOdd"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the match odd that needs to be deleted"
          required: true
          type: "number"
      responses:
        "200":
          description: "Deleted match odd"
        "500":
          description: "Failure of operation"
definitions:
    MatchInput:
      type: "object"
      properties:
        description:
          type: string
        date:
          type: string
          description: Date of match
          example: "2022-01-01"
        time:
          type: string
          description: Time of the match
          example: "21:00:00"
        teamA:
          type: string
        teamB:
          type: string
        sport:
          type: string
          description: currently supported sports
          enum:
            - "BASKETBALL"
            - "FOOTBALL"
    MatchResponse:
      type: "object"
      properties:
        id:
          type: number
        description:
          type: string
        date:
          type: string
          description: Date of match
          example: "2022-01-01"
        time:
          type: string
          description: Time of the match
          example: "21:00:00"
        teamA:
          type: string
        teamB:
          type: string
        sport:
          type: string
          description: currently supported sports
          enum:
            - "BASKETBALL"
            - "FOOTBALL"
        odds:
          type: array
          $ref:  "#/definitions/MatchOddResponse"
    MatchOddResponse:
      type: object
      properties:
        id:
          type: number
        specifier:
          type: string
        odd:
          type: number
    MatchOddInput:
      type: object
      properties:
        specifier:
          type: string
        odd:
          type: number


